bazel-contrib/rules_ruby

- docs/repository_rules.md
- examples/gem/WORKSPACE
- ruby/deps.bzl
- ruby/private/download.bzl
- ruby/private/download/BUILD.tpl
- ruby/toolchain.bzl
Fixes https://github.com/p0deje/rules_ruby/issues/3.
Introduce a "proxy repository" to register the toolchain without actually downloading it.
> lazily download ruby toolchain

- ruby/private/binary.bzl
Temporary workaround to support nested Gemfiles; a bit hacky since this expects a Gemfile in the transitive srcs. Ideally we'd want to provide this information via the rb_bundle repository rather than explicitly passing it in via `srcs`.
> support `rb_binary` with Gemfiles in subdirectory

- examples/gem/spec/BUILD
These made the latest main build red: https://github.com/p0deje/rules_ruby/actions/runs/6909216318/job/18800385795 Moderate timeout will give them 5min rather than 1min to complete.
Note, #18 will add buildifier which will sort these new attributes, so I didn't take any care what order they appear in.
> chore: extend timeout for some tests

- .pre-commit-config.yaml
- docs/BUILD
- examples/gem/ruby_version.bzl
- ruby/defs.bzl
- ruby/deps.bzl
- ruby/private/binary.bzl
- ruby/private/bundle.bzl
- ruby/private/download.bzl
- ruby/private/gem_build.bzl
- ruby/private/gem_push.bzl
- ruby/private/library.bzl
- ruby/private/providers.bzl
- ruby/private/test.bzl
- ruby/toolchain.bzl
So far this is just opt-in, you install from pre-commit.com and run 'pre-commit install' to get your commits formatted nicely. We can add some CI enforcement for this in a follow-up PR.
Ran 'pre-commit run --all-files' to do an initial pass over the repo and made it warning-clean.
> chore: introduce buildifier format/linter for starlark

- .gitattributes
- .github/workflows/release.yml
- .github/workflows/release_prep.sh
- CONTRIBUTING.md
It's now sufficient to just push a tag to the repository, this will create a release using GitHub actions with reasonable release notes, and it also uses a release artifact since GitHub doesn't guarantee stability of their archives.
This is taken from the https://github.com/bazel-contrib/rules-template which is maintained by experts on the Rules Authors SIG to make rules easy to maintain and also more consistent.
> chore: automate releases

- .github/workflows/BUILD.bazel
- .github/workflows/buildifier.yaml
- WORKSPACE
Matches how it's done in the bazel-contrib/rules-template
> chore: check buildifier on CI

- .bcr/README.md
- .bcr/config.yml
- .bcr/metadata.template.json
- .bcr/presubmit.yml
- .bcr/source.template.json
- .github/workflows/ci.yml
- MODULE.bazel
- docs/repository_rules.md
- examples/gem/MODULE.bazel
- examples/gem/WORKSPACE.bzlmod
- ruby/deps.bzl
- ruby/extensions.bzl
- ruby/private/bundle.bzl
- ruby/private/download.bzl
> feat: support bzlmod

- .github/workflows/ci.bazelrc
This is required by the reusable workflow used for releases. Fixes broken release build:
https://github.com/p0deje/rules_ruby/actions/runs/6947837138/job/18902520558
> chore: add bazelrc for CI

- .gitattributes
This is needed since we use the examples/gem folder as our artifact test on the bazel-central-registry presubmit.
> chore: include examples in release artifact

- .github/workflows/ci.yml
- docs/repository_rules.md
- ruby/BUILD
- ruby/deps.bzl
- ruby/extensions.bzl
- ruby/private/BUILD
- ruby/private/download.bzl
- ruby/private/toolchain.bzl
- ruby/private/toolchain/BUILD
- ruby/private/toolchain/repository_proxy.bzl
- ruby/private/toolchain/repository_proxy/BUILD.tpl
Allows to avoid downloading/installing Ruby interpreter at the expense of losing hermeticity and no Ruby version check.
```bazel
load("@rules_ruby//ruby:deps.bzl", "rb_register_toolchains")
rb_register_toolchains(
version = "system",
)
```
@kigster Does it look reasonable for your case of migrating from Bazelruby?
> Support registering system Ruby

- .github/workflows/ci.yml
- docs/rules.md
- examples/gem/lib/gem/BUILD
- examples/gem/lib/gem/add.rb
- ruby/private/BUILD
- ruby/private/binary.bzl
- ruby/private/binary/BUILD
- ruby/private/binary/binary.cmd.tpl
- ruby/private/binary/binary.sh.tpl
- ruby/private/binary/rlocation.bzl
- ruby/private/library.bzl
- ruby/private/providers.bzl
Allows to use an rb_binary() target as an input to a run_binary() rule
> feat: improve runfiles handling

- README.md
- docs/repository_rules.md
- examples/gem/MODULE.bazel
- ruby/deps.bzl
- ruby/private/toolchain.bzl
This is based on a couple of observations:
- The "name" provided by the user when calling a repository rule should result in a repository of exactly that name, otherwise there is a magical transformation that you have to track down from some documentation. `make_repo("foo") -> @foo//some:label`
- we already have a repository "rules_ruby" which is the one installed by the user to get this code, so it is confusing to use that name or a similar one for the repository containing the interpreter.
BREAKING CHANGE:
The name of the default generated repository to load the interpreter has changed from `rules_ruby_dist` to `ruby`, or from `[name]_dist` to `[name]` if you provided a different name.
> refactor: change naming of external repository

- .github/workflows/ci.yml
- README.md
- ruby/private/download.bzl
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
> feat: update Ruby to 3.3

- README.md
- ruby/private/binary.bzl
- ruby/private/binary/binary.cmd.tpl
- ruby/private/binary/binary.sh.tpl
- ruby/private/bundle_install.bzl
- ruby/private/download.bzl
- ruby/private/download/BUILD.tpl
- ruby/private/gem_install.bzl
- ruby/private/utils.bzl
- ruby/toolchain.bzl
This allows to build/run/test on the RBE environment at least for JRuby.
> feat: support RBE

- docs/repository_rules.md
- ruby/private/bundle_fetch.bzl
- ruby/private/bundle_fetch/gemfile_lock_parser.bzl
Our builds don't permit access to `rubygems.org` and this one is easy to fix.
> Add `bundler_remote` attribute to `rb_bundle_fetch`

- ruby/private/bundle_fetch.bzl
Follow-up to https://github.com/bazel-contrib/rules_ruby/pull/83 since I forgot to cherry-pick the changes that actually start using the checksums from my internal fork 🤦
> Actually use the bundler checksum

- docs/repository_rules.md
- ruby/private/bundle_install.bzl
- ruby/private/toolchain.bzl
Right now, we're overwriting `$PATH` regardless of what the user specifies in `env`. With this change, we use the user's provided value in addition to adding our own entry.
This is necessary for some gems that depend on system binaries. For example, the `pg` gem depends on `pg_config` binary.
Bazel already adds some standard directories like `/usr/local/bin` to `$PATH`. But, that isn't sufficient on recent versions of MacOS because Homebrew stores packages elsewhere (see https://github.com/bazelbuild/bazel/issues/12049).
This change allows users who are comfortable with not fully hermetic bundle builds to opt into it by tweaking `$PATH`.
> feat: allow customizing `$PATH` during `rb_bundle_fetch`

- examples/gem/.ruby-version
Switching to TruffleRuby was a mis-committed change. Fixes BCR CI from https://github.com/bazelbuild/bazel-central-registry/pull/1664
> revert: default toolchain is jruby

- ruby/private/download.bzl
Related to #125
Updates the method for determining the system Ruby path in `ruby/private/download.bzl`.
- Replaces the use of `repository_ctx.which("ruby")` with `repository_ctx.execute(["ruby", "-e", "puts RbConfig.ruby"])` to accurately determine the Ruby binary path when using the system Ruby.
- Implements error handling for the command execution, failing the build with a clear message if the system Ruby path cannot be determined.
- Maintains the symlink creation logic to link the determined Ruby directory to `dist/bin`, ensuring compatibility with existing setups.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/bazel-contrib/rules_ruby/issues/125?shareId=82c03088-9c65-4564-af8b-4c7aec83de72).
> fix: properly locate OS-installed `system` Ruby

- ruby/private/download.bzl
👋 I was looking at possible opportunities to speed up Ruby build time and this one seemed like a good candidate. I was able to shave off about 30 seconds by adding this flag to not compile docs material.
On my M3 Max laptop, installing Ruby 3.3.2 with current `main`:
```
0.08s user 0.12s system 0% cpu 1:21.58 total
```
With this change:
```
0.06s user 0.08s system 0% cpu 52.332 total
```
Another more extensible approach could be to make this part of a  configurable `configure` arg setting passed into the rules' toolchain config. But I thought perhaps this is just a good start to add this as a way to speed up the rules fetch in general, and I couldn't really think of a reason someone would want doc generation for the core Ruby itself in the context of a Bazel build.
> add `--disable-install-doc` to Ruby configure args to speed up installation time

- ruby/private/binary/binary.cmd.tpl
- ruby/private/binary/binary.sh.tpl
This eliminates the following warning:
```
`/` is not writable.
Bundler will use `/tmp/bundler20290814-15-18gxxtn15' as your home directory temporarily.
`/` is not writable.
Bundler will use `/tmp/bundler20290814-15-1tue52e15' as your home directory temporarily.
```
> Set `$HOME` to `$TEST_TMPDIR` in test targets

- docs/rules.md
- ruby/private/binary.bzl
- ruby/private/gem_build.bzl
- ruby/private/gem_push.bzl
I missed a couple spots where we should be using the override toolchain in https://github.com/bazel-contrib/rules_ruby/pull/140.
This time, I audited all the places we have a `ctx.toolchains["@rules_ruby//ruby:toolchain_type"]` and made sure that we use the override toolchain in them.
Without this change, binary targets like `@bundle//:rubocop` can end up pointing to a Ruby version that isn't actually in the runfiles for the target.
> fix: use override Ruby toolchain consistently

- README.md
This should fix CI failures like https://github.com/bazelbuild/bazel-central-registry/pull/3475
> chore: return `WORKSPACE` for Bazel 6

- docs/repository_rules.md
- examples/gem/spec/BUILD
- examples/gem/spec/env_spec.rb
- ruby/private/download.bzl
- ruby/private/download/BUILD.engine.tpl
- ruby/private/toolchain.bzl
Exposes Ruby engine targets to `select()` depending on installed Ruby interpreter:
`BUILD`:
```bazel
rb_library(
name = "my_lib",
srcs = ["my_lib.rb"],
deps = select({
"@ruby//engine:jruby": [":my_jruby_lib"],
"@ruby//engine:truffleruby": ["//:my_truffleruby_lib"],
"@ruby//engine:ruby": ["//:my__lib"],
"//conditions:default": [],
}),
)
```
> feat: expose Ruby engine configuration

- renovate.json
Direct dependencies should not be updated without a good reason (see MODULE.bazel).
> chore(deps): ignore rules_cc and rules_java

- examples/native_ext/MODULE.bazel
- ruby/private/binary.bzl
run_binary() uses files from DefaultInfo to lay out the tree of dependencies for executable.
This was accidentally broken in 5008f8a8355b4927bc4564c39b109dfe36199994.
> fix: include files in rb_binary DefaultInfo

- .bcr/presubmit.yml
- .github/workflows/ci.yml
- examples/gem/BUILD
- ruby/private/bundler_checksums.bzl
- ruby/private/download.bzl
Looks to be an environment issue - the same target works on GitHub Actions CI while fails on Bazel BCR Presubmit.
> ci: exclude sh_test from Bazel CI

- ruby/private/download/BUILD.tpl
Prevent the implicit inclusion of JRuby's jars into jars made from .java files that have a compile-time dependency on JRuby.
Addresses the root cause of https://github.com/protocolbuffers/protobuf/issues/21369 and will enable the eventual rollback of https://github.com/protocolbuffers/protobuf/pull/21416.
> Apply `neverlink = True` to `jars`

- ruby/private/binary.bzl
- ruby/private/gem_push.bzl
This is required in Bazel 8.3.0, where this target gained runfiles.
> Fix runfiles merging for `@bazel_tools//tools/bash/runfiles`

- .github/workflows/ci.yml
- examples/gem/.bazelrc
- examples/gem/MODULE.bazel
Fixes CI failures on https://github.com/bazelbuild/bazel-central-registry/pull/5034
See commits for details.
> chore: fix 0.20.0 release on BCR
